# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

schedules:
- cron: "0 23 * * *"
  displayName: 'Daily 11 PM run'
  branches:
    include:
    - main
  always: true
pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22'
  displayName: 'Install Node.js'
- script: npm ci
  displayName: 'npm ci'
- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'
- script: npx play  wright test --reporter=allure-playwright,html
  displayName: 'Run Playwright tests'
  env:
    CI: 'true'
- task: PublishAllureReport@1
  inputs:
    allureVersion: '2.27.0'
    testResultsDir: '$(System.DefaultWorkingDirectory)/allure-results'
  displayName: 'Publish Report'
  condition: always()
